str1=("Python is a high level programming language")
print(str1)
print(len(str1))
print(str1[1])
print(str1[-3])
print(str1[0:3])
print(str1[:5])
print(str1[::2])
print(str1.count("l"))
print(str1.find("is"))
print(str1.lower())
print(str1.capitalize())
print(str1.title())
print(str1.swapcase())